<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\LabTest;

class LabTestSeeder extends Seeder
{
    public function run(): void
    {
        $tests = [
            ['name' => 'ACTIVE PARTIAL THROMBOPLASTIN TIME (APTT)', 'price' => 465, 'category' => 'Blood Tests'],
            ['name' => 'ANTI MULLERIAN HORMONE(AMH)', 'price' => 1800, 'category' => 'Blood Tests'],
            ['name' => 'BLOOD GROUP & RH TYPE', 'price' => 200, 'category' => 'Blood Tests'],
            ['name' => 'COPPER - SERUM', 'price' => 2250, 'category' => 'Blood Tests'],
            ['name' => 'DENGUE PROFILE (IgG, IgM & Ns1Ag)', 'price' => 250, 'category' => 'Blood Tests'],
            ['name' => 'ESR', 'price' => 150, 'category' => 'Blood Tests'],
            ['name' => 'HAEMOGLOBIN (Hb)', 'price' => 130, 'category' => 'Blood Tests'],
            ['name' => 'HIGH SENSITIVE CRP (hsCRP)', 'price' => 1000, 'category' => 'Blood Tests'],
            ['name' => 'MALARIAL PARASITE (CARD TEST)', 'price' => 200, 'category' => 'Blood Tests'],
            ['name' => 'PACKED CELL VOLUME (PCV)', 'price' => 190, 'category' => 'Blood Tests'],
            ['name' => 'PERIPHERAL SMEAR', 'price' => 200, 'category' => 'Blood Tests'],
            ['name' => 'PLATELET COUNT, EDTA WHOLE BLOOD', 'price' => 200, 'category' => 'Blood Tests'],
            ['name' => 'PROTHROMBIN TIME (PT)', 'price' => 465, 'category' => 'Blood Tests'],
            ['name' => 'RETICULOCYTE COUNT', 'price' => 450, 'category' => 'Blood Tests'],
            ['name' => 'TOTAL COUNT (TC)', 'price' => 200, 'category' => 'Blood Tests'],
            ['name' => 'CULTURE, URINE WITH SUSCEPTIBILITY', 'price' => 950, 'category' => 'Blood Tests'],
            ['name' => 'CBC WITH ESR', 'price' => 500, 'category' => 'Blood Tests'],
            ['name' => 'CBC-5, EDTA WHOLE BLOOD', 'price' => 400, 'category' => 'Blood Tests'],
            ['name' => 'ALPHA-FETOPROTEIN, SERUM', 'price' => 1050, 'category' => 'Blood Tests'],
            ['name' => 'ABSOLUTE EOSINOPHIL COUNT', 'price' => 200, 'category' => 'Blood Tests'],
            ['name' => 'ABSOLUTE BASOPHIL COUNT', 'price' => 385, 'category' => 'Blood Tests'],
            ['name' => 'ABSOLUTE LYMPHOCYTE COUNT', 'price' => 385, 'category' => 'Blood Tests'],
            ['name' => 'ABSOLUTE MONOCYTE COUNT', 'price' => 385, 'category' => 'Blood Tests'],
            ['name' => 'ACID FAST BACILLI SMEAR', 'price' => 290, 'category' => 'Blood Tests'],
            ['name' => 'TOTAL IGE, SERUM', 'price' => 900, 'category' => 'Blood Tests'],
            ['name' => 'ANEMIA PROFILE I', 'price' => 1920, 'category' => 'Blood Tests'],
            ['name' => 'QUADRUPLE MARKER TEST BY TRF METHOD, SERUM', 'price' => 4200, 'category' => 'Blood Tests'],
            ['name' => 'THROAT SWAB CULTURE + SUSCEPTIBILITY', 'price' => 950, 'category' => 'Blood Tests'],
            ['name' => 'H1N1 /SWINE FLU BY PCR', 'price' => 2800, 'category' => 'Blood Tests'],
            ['name' => 'STOOL FOR CULTURE & SENSITIVITY, AEROBIC', 'price' => 950, 'category' => 'Blood Tests'],
            ['name' => 'THYROID ANTIBODIES, SERUM', 'price' => 2900, 'category' => 'Blood Tests'],
            ['name' => 'LAMOTRIGINE,SERUM', 'price' => 5850, 'category' => 'Blood Tests'],
            ['name' => 'HEMOGLOBIN VARIANT ANALYSIS - BLOOD', 'price' => 900, 'category' => 'Blood Tests'],
            ['name' => 'HEPATITIS B E ANTIBODY, SERUM', 'price' => 1150, 'category' => 'Blood Tests'],
            ['name' => 'HEPATITIS B E ANTIGEN, SERUM', 'price' => 1150, 'category' => 'Blood Tests'],
            ['name' => 'ARTHRITIS PANEL', 'price' => 2900, 'category' => 'Blood Tests'],
            ['name' => 'HLA B27 BY PCR', 'price' => 4000, 'category' => 'Blood Tests'],
            ['name' => 'RUBELLA IGG ANTIBODIES, SERUM', 'price' => 950, 'category' => 'Blood Tests'],
            ['name' => 'ANTI NUCLEAR ANTIBODY, IFA, SERUM', 'price' => 1400, 'category' => 'Blood Tests'],
            ['name' => 'BT, CT', 'price' => 180, 'category' => 'Blood Tests'],
            ['name' => 'GASTRIN, SERUM', 'price' => 1800, 'category' => 'Blood Tests'],
            ['name' => 'BLOOD CULTURE - BACTEC PLUS', 'price' => 1300, 'category' => 'Blood Tests'],
            ['name' => 'PROCALCITONIN, SERUM', 'price' => 5600, 'category' => 'Blood Tests'],
            ['name' => 'GLIADIN II- IGA (DGP) ANTIBODIES,SERUM', 'price' => 3600, 'category' => 'Blood Tests'],
            ['name' => 'GLIADIN II- IGG (DGP) ANTIBODIES, SERUM', 'price' => 3600, 'category' => 'Blood Tests'],
            ['name' => 'TISSUE TRANSGLUTAMINASE IGA, SERUM', 'price' => 1700, 'category' => 'Blood Tests'],
            ['name' => 'HLA-B27, FLOW CYTOMETRY, BLOOD', 'price' => 3300, 'category' => 'Blood Tests'],
            ['name' => 'GLUCOSE, URINE', 'price' => 80, 'category' => 'Blood Tests'],
            ['name' => 'TBFERON (M TUBERCULOSIS IGRA)', 'price' => 2100, 'category' => 'Blood Tests'],
            ['name' => 'RUBELLA IGM, SERUM', 'price' => 950, 'category' => 'Blood Tests'],
            ['name' => 'COPPER, SERUM', 'price' => 2400, 'category' => ''],
            ['name' => 'LH, FSH, PROLACTIN, SERUM', 'price' => 1500, 'category' => 'Blood Tests'],
            ['name' => 'FREE TESTOSTERONE, SERUM', 'price' => 2100, 'category' => 'Blood Tests'],
            ['name' => 'HBV VIRAL LOAD BY REAL TIME PCR', 'price' => 4700, 'category' => 'Blood Tests'],
            ['name' => 'RUBELLA IGG & IGM, SERUM', 'price' => 1550, 'category' => 'Blood Tests'],
            ['name' => 'X-ray Right shoulder ap/Lateral view', 'price' => 800, 'category' => 'Xray'],
            ["name" => "HOMOCYSTEINE, SERUM/PLASMA", "price" => 1400, "category" => "Blood Tests"],
            ["name" => "HEART ASSURE (HIGH-SENSITIVE CARDIAC TROPONIN I)", "price" => 1820, "category" => "Blood Tests"],
            ["name" => "PROSTATE SPECIFIC ANTIGEN, SERUM", "price" => 1050, "category" => "Blood Tests"],
            ["name" => "DEHYDROEPIANDROSTERONE-S, SERUM", "price" => 1250, "category" => "Blood Tests"],
            ["name" => "DENGUE VIRUS IGM, SERUM", "price" => 600, "category" => "Blood Tests"],
            ["name" => "DENGUE VIRUS IGG, SERUM", "price" => 600, "category" => "Blood Tests"],
            ["name" => "REDUCING SUBSTANCES, STOOL", "price" => 275, "category" => "Blood Tests"],
            ["name" => "FECAL CALPROTECTIN, STOOL", "price" => 3200, "category" => "Blood Tests"],
            ["name" => "Anti Gliadin IgA Antibodies Test", "price" => 2500, "category" => "Blood Tests"],
            ["name" => "HELICOBACTER PYLORI ANTIGEN DETECTION", "price" => 1600, "category" => "Blood Tests"],
            ["name" => "N-TERMINAL PRO B-TYPE NATRIURETIC PEPTIDE, SERUM", "price" => 4300, "category" => "Blood Tests"],
            ["name" => "CA 19-9, SERUM", "price" => 1700, "category" => "Blood Tests"],
            ["name" => "XPERT MTB/RIF - PULMONARY", "price" => 2416, "category" => "Blood Tests"],
            ["name" => "TACROLIMUS, EDTA WHOLE BLOOD", "price" => 2100, "category" => "Blood Tests"],
            ["name" => "ANGIOTENSIN CONVERTING ENZYME, SERUM", "price" => 1400, "category" => "Blood Tests"],
            ["name" => "TOTAL BILE ACIDS, SERUM", "price" => 2300, "category" => "Blood Tests"],
            ["name" => "HEP B EVALUATION", "price" => 1700, "category" => "Blood Tests"],
            ["name" => "OSMOLALITY, URINE", "price" => 1100, "category" => "Blood Tests"],
            ["name" => "FLU REAL TIME PCR", "price" => 2500, "category" => "Blood Tests"],
            ["name" => "HEPATITIS E IGM, SERUM", "price" => 1900, "category" => "Blood Tests"],
            ["name" => "SODIUM, RANDOM, URINE", "price" => 120, "category" => "Blood Tests"],
            ["name" => "CERULOPLASMIN, SERUM", "price" => 1400, "category" => "Blood Tests"],
            ["name" => "Estimated Glomerular Filtration Rate (eGFR)", "price" => 255, "category" => "Blood Tests"],
            ["name" => "ANTI MITOCHONDRIAL ANTIBODY, SERUM", "price" => 2700, "category" => "Blood Tests"],
            ["name" => "SECOND TRIMESTER QUADRUPLE MARKER", "price" => 4200, "category" => "Blood Tests"],
            ["name" => "C PEPTIDE, SERUM", "price" => 1400, "category" => "Blood Tests"],
            ["name" => "VIRAL SCREEN", "price" => 999, "category" => "Blood Tests"],
            ["name" => "ZIEL-NEELSEN TECHNIQUE FOR ACID FAST BACILLI", "price" => 410, "category" => "Blood Tests"],
            ["name" => "Homocysteine Test", "price" => 900, "category" => "Blood Tests"],
            ["name" => "Apolipoprotein A-I Test", "price" => 500, "category" => "Blood Tests"],
            ["name" => "Apolipoprotein B Test", "price" => 500, "category" => "Blood Tests"],
            ["name" => "C Peptide Random Test", "price" => 1050, "category" => "Blood Tests"],
            ["name" => "PTH(INTACT),EDTA & CALCIUM, SERUM", "price" => 2200, "category" => "Blood Tests"],
            ["name" => "TRYPTASE, SERUM", "price" => 2300, "category" => "Blood Tests"],
            ["name" => "VALPROIC ACID, SERUM", "price" => 1150, "category" => "Blood Tests"],
            ["name" => "GAD GLUTAMIC ACID DECARBOXYLASE-65", "price" => 6440, "category" => "Blood Tests"],
            ["name" => "ZINC TRANSPORTER 8 (ZNT8) ANTIBBODY", "price" => 4330, "category" => "Blood Tests"],
            ["name" => "ANTI INSULIN ANTIBODIES", "price" => 1990, "category" => "Blood Tests"],
            ["name" => "COMPLETE BLOOD COUNT (CBC)-5", "price" => 400, "category" => "Blood Tests"],
            ["name" => "ALANINE AMINOTRANSFERASE (SGPT/ALT)", "price" => 200, "category" => "Blood Tests"],
            ["name" => "ALKALINE PHOSPHATASE (ALP)", "price" => 200, "category" => "Blood Tests"],
            ["name" => "AMMONIA", "price" => 1100, "category" => "Blood Tests"],
            ["name" => "FASTING BLOOD SUGAR (FBS)", "price" => 50, "category" => "Blood Tests"],
            ["name" => "FASTING SERUM INSULIN", "price" => 1000, "category" => "Blood Tests"],
            ["name" => "GAMMA GLUTAMYL TRANSPEPTIDASE (GGT)", "price" => 200, "category" => "Blood Tests"],
            ["name" => "GLUCOSE CHALLENGE TEST (GCT)", "price" => 100, "category" => "Blood Tests"],
            ["name" => "GLYCOSYLATED HEMOGLOBIN(HBA1C), EDTA WHOLE BLOOD", "price" => 450, "category" => "Blood Tests"],
            ["name" => "GROWTH HORMONE (GH)", "price" => 900, "category" => "Blood Tests"],
            ["name" => "INTERLEUKIN 6 (IL-6)", "price" => 3300, "category" => "Blood Tests"],
            ["name" => "IONIZED CALCIUM", "price" => 600, "category" => "Blood Tests"],
            ["name" => "IRON", "price" => 450, "category" => "Blood Tests"],
            ["name" => "IRON PROFILE", "price" => 550, "category" => "Blood Tests"],
            ["name" => "LDH", "price" => 450, "category" => "Blood Tests"],
            ["name" => "LIPASE", "price" => 750, "category" => "Blood Tests"],
            ["name" => "LIPID PROFILE TEST (LPT)", "price" => 450, "category" => "Blood Tests"],
            ["name" => "LITHIUM", "price" => 700, "category" => "Blood Tests"],
            ["name" => "LIVER FUNCTION TEST (LFT)", "price" => 700, "category" => "Blood Tests"],
            ["name" => "POST PRANDIAL BLOOD SUGAR (PPBS)", "price" => 50, "category" => "Blood Tests"],
            ["name" => "PROTEIN / CREATININE RATIO - URINE (RANDOM)", "price" => 310, "category" => "Blood Tests"],
            ["name" => "RANDOM BLOOD SUGAR (RBS)", "price" => 50, "category" => "Blood Tests"],
            ["name" => "RHEUMATOID FACTOR (RA)", "price" => 600, "category" => "Blood Tests"],
            ["name" => "SERUM ALBUMIN", "price" => 200, "category" => "Blood Tests"],
            ["name" => "SERUM AMYLASE", "price" => 550, "category" => "Blood Tests"],
            ["name" => "SERUM BILIRUBIN", "price" => 149, "category" => "Blood Tests"],
            ["name" => "SERUM CALCIUM", "price" => 200, "category" => "Blood Tests"],
            ["name" => "SERUM CHLORIDE", "price" => 120, "category" => "Blood Tests"],
            ["name" => "SERUM CREATININE", "price" => 200, "category" => "Blood Tests"],
            ["name" => "SERUM ELECTROLYTES", "price" => 300, "category" => "Blood Tests"],
            ["name" => "SERUM FERRITIN", "price" => 649, "category" => "Blood Tests"],
            ["name" => "SERUM GLOBULIN", "price" => 200, "category" => "Blood Tests"],
            ["name" => "SERUM MAGNESIUM", "price" => 199, "category" => "Blood Tests"],
            ["name" => "SERUM PHOSPHORUS", "price" => 255, "category" => "Blood Tests"],
            ["name" => "SERUM POTASSIUM(K+)", "price" => 120, "category" => "Blood Tests"],
            ["name" => "SERUM SODIUM (Na+)", "price" => 120, "category" => "Blood Tests"],
            ["name" => "SERUM TRIGLYCERIDES", "price" => 200, "category" => "Blood Tests"],
            ["name" => "SERUM URIC ACID", "price" => 200, "category" => "Blood Tests"],
            ["name" => "TOTAL PROTEIN", "price" => 180, "category" => "Blood Tests"],
            ["name" => "TRANSFERRIN", "price" => 1350, "category" => "Blood Tests"],
            ["name" => "TROPONIN T", "price" => 1800, "category" => "Blood Tests"],
            ["name" => "LACTATE DEHYDROGENASE", "price" => 430, "category" => "Blood Tests"],
            ["name" => "INTERLEUKIN 6, PLASMA", "price" => 3300, "category" => "Blood Tests"],
            ["name" => "INTERLEUKIN 6, SERUM", "price" => 3300, "category" => "Blood Tests"],
            ["name" => "L-LACTATE, CSF", "price" => 1300, "category" => "Blood Tests"],
            ["name" => "L-LACTATE, FLUORIDE PLASMA", "price" => 1300, "category" => "Blood Tests"],
            ["name" => "MAGNESIUM, 24HRS URINE", "price" => 410, "category" => "Blood Tests"],
            ["name" => "LUPUS ANTICOAGULANT", "price" => 2400, "category" => "Blood Tests"],
            ["name" => "FATTY LIVER INDEX,SERUM", "price" => 600, "category" => "Blood Tests"],
            ["name" => "KIDNEY PROFILE I (KFT)", "price" => 750, "category" => "Blood Tests"],
            ["name" => "Cardiac Risk Markers- Advanced", "price" => 1799, "category" => "Blood Tests"],
            ["name" => "APO A1/B Ratio", "price" => 1600, "category" => "Blood Tests"],
            ["name" => "ANTI-MOG ANTIBODY", "price" => 4800, "category" => "Blood Tests"],
            ["name" => "ANTI-AQP4 (NMO-IGG) ANTIBODY, SERUM/CSF", "price" => 4800, "category" => "Blood Tests"],
            ["name" => "ANTI-SS-A (SS-A 52 AND SS-A 60) ANTIBODY, SERUM", "price" => 1680, "category" => "Blood Tests"],
            ["name" => "DEHYDROEPIANDROSTERONE SULFATE (DHEA-S)(LCMS) DEHYDROEPIANDROSTERONE SULPHATE(DHEAS)", "price" => 1190, "category" => "Blood Tests"],
            ["name" => "ESTRADIOL (E2), SERUM ESTRADIOL (E2) Biochemistry CLIA Serum", "price" => 500, "category" => "Blood Tests"],
            ["name" => "TESTOSTERONE TOTAL (LCMS) TESTOSTERONE TOTAL (LCMS)", "price" => 1980, "category" => "Blood Tests"],
            ["name" => "ORAL GLUCOSE TOLERANCE TEST (GTT) 3", "price" => 300, "category" => "Blood Tests"],
            ["name" => "125-DI HYDROXY CHOLECALCIFEROL (VITAMIN D3)", "price" => 4100, "category" => "Blood Tests"],
            ["name" => "25-HYDROXY VITAMIN D", "price" => 899, "category" => "Blood Tests"],
            ["name" => "AFP", "price" => 900, "category" => "Blood Tests"],
            ["name" => "ESTRADIOL", "price" => 750, "category" => "Blood Tests"],
            ["name" => "FSH", "price" => 500, "category" => "Blood Tests"],
            ["name" => "FT3", "price" => 450, "category" => "Blood Tests"],
            ["name" => "FT4", "price" => 450, "category" => "Blood Tests"],
            ["name" => "HEPATITIS A IGM, SERUM", "price" => 1500, "category" => "Blood Tests"],
            ["name" => "PROGESTERONE, SERUM", "price" => 850, "category" => "Blood Tests"],
            ["name" => "PROLACTIN", "price" => 300, "category" => "Blood Tests"],
            ["name" => "Prostate Specific Antigen (PSA) Total", "price" => 900, "category" => "Blood Tests"],
            ["name" => "T3", "price" => 250, "category" => "Blood Tests"],
            ["name" => "T4", "price" => 250, "category" => "Blood Tests"],
            ["name" => "THYROID PROFILE (T3, T4, TSH)", "price" => 450, "category" => "Blood Tests"],
            ["name" => "TSH", "price" => 300, "category" => "Blood Tests"],
            ["name" => "VITAMIN B-12", "price" => 799, "category" => "Blood Tests"],
            ["name" => "TRIIDOTHYRONINE-FREE (FT3) - SERUM", "price" => 450, "category" => "Blood Tests"],
            ["name" => "TROPONIN", "price" => 650, "category" => "Blood Tests"],
            ["name" => "TROPONIN T - HS, SERUM", "price" => 1900, "category" => "Blood Tests"],
            ["name" => "THYROID PROFILE II (FT3,FT4 & TSH)", "price" => 650, "category" => "Blood Tests"],
            ["name" => "CULTURE & SENSITIVITY - URINE", "price" => 850, "category" => "Blood Tests"],
            ["name" => "GRAM STAIN", "price" => 260, "category" => "Blood Tests"],
            ["name" => "RAPID TYPHI DOT", "price" => 400, "category" => "Blood Tests"],
            ["name" => "HCV ABS, SERUM", "price" => 1500, "category" => "Blood Tests"],
            ["name" => "C-REACTIVE PROTEIN (CRP)", "price" => 500, "category" => "Blood Tests"],
            ["name" => "CD4", "price" => 1150, "category" => "Blood Tests"],
            ["name" => "FOLIC ACID", "price" => 1200, "category" => "Blood Tests"],
            ["name" => "HCV CLIA", "price" => 1200, "category" => "Blood Tests"],
            ["name" => "HEPATITIS B SURFACE ANTIGEN (HBsAg) (CARD)", "price" => 450, "category" => "Blood Tests"],
            ["name" => "HIGH SENSITIVE C-REACTIVE PROTEIN", "price" => 900, "category" => "Blood Tests"],
            ["name" => "HIV 1 & 2", "price" => 450, "category" => "Blood Tests"],
            ["name" => "HIV ELISA", "price" => 750, "category" => "Blood Tests"],
            ["name" => "VDRL, SERUM", "price" => 350, "category" => "Blood Tests"],
            ["name" => "WEIL FELIX TEST", "price" => 1050, "category" => "Blood Tests"],
            ["name" => "WIDAL SLIDE", "price" => 350, "category" => "Blood Tests"],
            ["name" => "HEPATITIS B SURFACE ANTIGEN, SERUM", "price" => 600, "category" => "Blood Tests"],
            ["name" => "VDRL, SERUM", "price" => 250, "category" => "Blood Tests"],
            ["name" => "DENGUE NS1 ANTIGEN TEST, SERUM", "price" => 600, "category" => "Blood Tests"],
            ["name" => "HCV", "price" => 1200, "category" => "Blood Tests"],
            ["name" => "CHIKUNGUNYA IGM ANTIBODIES RAPID, SERUM", "price" => 825, "category" => "Blood Tests"],
            ["name" => "COMPLETE URINE ANALYSIS", "price" => 200, "category" => "Blood Tests"],
            ["name" => "FNAC", "price" => 4100, "category" => "Blood Tests"],
            ["name" => "INDIRECT COOMB'S TEST (ICT)", "price" => 530, "category" => "Blood Tests"],
            ["name" => "SEMEN ANALYSIS", "price" => 1000, "category" => "Blood Tests"],
            ["name" => "STOOL ANALYSIS", "price" => 180, "category" => "Blood Tests"],
            ["name" => "STOOL FOR OCCULT BLOOD", "price" => 180, "category" => "Blood Tests"],
            ["name" => "URINE MICROALBUMINUREA", "price" => 450, "category" => "Blood Tests"],
            ["name" => "MICROALBUMIN, URINE", "price" => 550, "category" => "Blood Tests"],

        ];

        foreach ($tests as $test) {
            LabTest::create($test);
        }
    }
}
